server:
  port: 5008
list_wa:
  - name: malik
    number: 6289697338821
    list_server:
      - all
  - name: amal
    number: 628980185458
    list_server:
      - arm
      - hipmi
      - ninox-fox
  - name: bagas
    number: 6282340374412
    list_server:
      - hipmi
  - name: lukman
    number: 6287701790942
    list_server:
      - arm
      - ninox-fox
list_server:
  - id: str_5001
    name: str
    branch: build
    port: 5001

  - id: arm_5004
    name: arm
    branch: build
    port: 5004

  - id: hipmi_5005
    name: hipmi
    branch: build
    port: 5005

  - id: raven_stone_5007
    name: raven-stone
    branch: build
    port: 5007

  - id: explore_3000
    name: explore-tropica
    branch: build
    port: 3000

  - id: ninox-fox_5010
    name: ninox-fox
    branch: build
    port: 5010

  - id: monit_5011
    name: monit
    branch: build
    port: 5011

  - id: raven-stone2_5013
    name: raven-stone2
    branch: build
    port: 5013
  
  - id: arm2_5014
    name: arm2
    branch: build
    port: 5014

